/**
 * Writes public/sitemap.xml from the same SEO lists Astro SSG emits.
 * Run before build: node scripts/generate-sitemap.mjs
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { listSeoRoutes, listSeoRegions, listSeoCorridors } from '../src/lib/seo-routes.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ORIGIN = 'https://nexttrain.co.za';
const today = new Date().toISOString().slice(0, 10);

const core = [
  { loc: `${ORIGIN}/`, changefreq: 'daily', priority: '1.0' },
  { loc: `${ORIGIN}/guide.html`, changefreq: 'weekly', priority: '0.9' },
  { loc: `${ORIGIN}/map.html`, changefreq: 'weekly', priority: '0.85' },
  { loc: `${ORIGIN}/routes.html`, changefreq: 'weekly', priority: '0.85' },
];

const regionUrls = listSeoRegions().map((r) => ({
  loc: `${ORIGIN}/regions/${r.slug}.html`,
  changefreq: 'weekly',
  priority: '0.8',
}));

const corridorUrls = listSeoCorridors().map((c) => ({
  loc: `${ORIGIN}/corridors/${c.slug}.html`,
  changefreq: 'weekly',
  priority: '0.78',
}));

const routeUrls = listSeoRoutes().map(({ seed }) => ({
  loc: `${ORIGIN}/routes/${seed.slug}.html`,
  changefreq: 'weekly',
  priority: '0.75',
}));

const urls = [...core, ...regionUrls, ...corridorUrls, ...routeUrls];
const body = urls
  .map(
    (u) => `  <url>
    <loc>${u.loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`
  )
  .join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by scripts/generate-sitemap.mjs — do not hand-edit.
  Public indexable URLs only. Private ops pages (status, marketing) omitted.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;

writeFileSync(join(ROOT, 'public', 'sitemap.xml'), xml, 'utf8');
console.log(
  `sitemap.xml: ${urls.length} URLs (${regionUrls.length} regions, ${corridorUrls.length} corridors, ${routeUrls.length} routes)`
);
